version: "3.8"
services:
  psql:
    build: ./docker/psql
    image: drbwg_psql:1.0.0
    container_name: drbwg-psql-con
    environment:
      POSTGRES_USER: drbwg
      POSTGRES_PASSWORD: drbwg-password
    ports:
    - "5432:5432"
    volumes:
      - "./volume/psql:/var/lib/postgresql/data"

  notification:
    build:
      context: .
      dockerfile: notification.Dockerfile
    image: drbwg_notification
    depends_on:
      - psql
    environment:
      DRBWG_TOKEN: ${DRBWG_TOKEN}
      PSQL_URI: postgresql://drbwg:drbwg-password@drbwg-psql-con:5432

  bot:
    build: .
    image: drbwg_bot
    depends_on:
      - psql
    environment:
      DRBWG_TOKEN: ${DRBWG_TOKEN}
      PSQL_URI: postgresql://drbwg:drbwg-password@drbwg-psql-con:5432